apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv
  namespace: microservices
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/kafka-data
  storageClassName: local-storage
---
# Sử dụng emptyDir thay vì hostPath để tránh lỗi permission trên Windows
# Với production, nên sử dụng StorageClass phù hợp

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-pvc
  namespace: microservices
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""  # Sử dụng default storage class
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-pv
  namespace: microservices
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/zookeeper-data
  storageClassName: local-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper-pvc
  namespace: microservices
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""  # Sử dụng default storage class 